AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "doc/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

plugins:
  - rubocop-minitest
  - rubocop-rake

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
